# numpy 第一课：数组创建 + 索引 + reshape

**numpy 是什么（人话版）**：Python 列表的「涡轮增压版」。列表能装任何东西（数字、字符串、乱七八糟），
但 numpy 数组只能装同一种类型，换来的是**整体计算 + 快 100 倍**。
AI/机器学习的所有计算（包括你 v1 项目里的 sklearn）底层都是 numpy。

> 今天 1 小时目标：学会 3 个操作——**创建数组、取数（索引）、改形状（reshape）**
> 每格代码下面都写了「预期输出」，跑完自己对一下，不一致就停下来想。

In [ ]:
# 第 1 步：import（每次用 numpy 都要先喊它）
import numpy as np

# 创建数组的 4 种姿势
a = np.array([1, 2, 3, 4, 5])        # 用列表创建
b = np.arange(0, 10, 2)              # 数数：从 0 数到 10（不含10），每次 +2
c = np.linspace(0, 1, 5)             # 在 0 到 1 之间均匀取 5 个数
d = np.zeros(4)                      # 4 个 0
e = np.ones((2, 3))                  # 2 行 3 列的 1

print('a =', a)
print('b =', b)
print('c =', c)
print('d =', d)
print('e =')
print(e)

# 预期输出：
# a = [1 2 3 4 5]
# b = [0 2 4 6 8]
# c = [0.   0.25 0.5  0.75 1.  ]
# d = [0. 0. 0. 0.]
# e =
# [[1. 1. 1.]
#  [1. 1. 1.]]

In [ ]:
# 第 2 步：索引和切片（就是 v1 里 X[:, 2] 的秘密）
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

print('M 的形状 shape =', M.shape)      # (3, 3) = 3 行 3 列
print('第 0 行 =', M[0])                # 从 0 开始数！
print('第 0 行第 1 列 =', M[0, 1])      # 行, 列
print('第 1 列全部 =', M[:, 1])         # 冒号 = 全部行，取第 1 列
print('前 2 行 =', M[:2])               # 冒号左边留空 = 从头开始

# 预期输出：
# M 的形状 shape = (3, 3)
# 第 0 行 = [1 2 3]
# 第 0 行第 1 列 = 2
# 第 1 列全部 = [2 5 8]
# 前 2 行 = [[1 2 3]
#  [4 5 6]]

In [ ]:
# 第 3 步：reshape —— 改形状（v1 里 reshape(-1, 1) 的秘密）
v = np.arange(0, 6)          # [0 1 2 3 4 5]
print('v =', v, '形状:', v.shape)

v2 = v.reshape(2, 3)         # 变 2 行 3 列
print('reshape(2,3):')
print(v2)

v3 = v.reshape(-1, 1)        # -1 = 让 numpy 自己算，这里变成 6 行 1 列
print('reshape(-1,1):')
print(v3)
print('新形状:', v3.shape)

# 预期输出：
# v = [0 1 2 3 4 5] 形状: (6,)
# reshape(2,3):
# [[0 1 2]
#  [3 4 5]]
# reshape(-1,1):
# [[0]
#  [1]
#  [2]
#  [3]
#  [4]
#  [5]]
# 新形状: (6, 1)

# 为什么 v1 要 reshape(-1, 1)？
# sklearn 要求：每个样本是「一行」，即二维 (样本数, 特征数)
# 一个特征也要变成一列：442 个样本 → (442, 1)

## 🎯 挑战任务（核心逻辑自己写！）

下面的代码**只给脚手架，填空由你完成**——先自己想，别往下翻答案：

1. 用 `np.arange` 创建 `0 到 9` 的数组，命名 `x`
2. 把 `x` 变成 **2 行 5 列**，命名 `X2`
3. 取出 `X2` 的**第 1 列**（所有行）存为 `col`，打印它
4. 打印 `X2.shape` 验证形状

写完后运行，预期输出：
```
第 1 列 = [1 3 5 7 9]
X2 形状 = (2, 5)
```

In [ ]:
# ===== 挑战区：填空 =====
import numpy as np

# 1. 创建 0 到 9 的数组
x = np.arange(___)          # 填什么？

# 2. 变成 2 行 5 列
X2 = x.reshape(___)         # 填什么？

# 3. 取出第 1 列（所有行）
col = X2[:, ___]            # 填什么？
print('第 1 列 =', col)

# 4. 验证形状
print('X2 形状 =', X2.shape)

## 📝 盲写检查（不看代码，先写答案再运行）

在下面这个 cell 里，**凭记忆**写出：

1. `np.linspace(0, 10, 11)` 会输出什么？
2. `np.zeros(3)` 会输出什么？
3. 一个 (4, 3) 数组的 `shape` 是多少？

先在纸上/脑子里写答案，再运行验证。写错了没事——**错的地方就是你今天的收获**。

In [ ]:
# ===== 盲写验证区：写完先别跑，自己先猜 =====
import numpy as np

print(np.linspace(0, 10, 11))
print(np.zeros(3))
print(np.ones((4, 3)).shape)